name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Use Environment Secrets
        env:
          DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}
          TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
          FACEBOOK_SECRET: ${{ secrets.FACEBOOK_SECRET }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
        run: |
          echo "Connecting to database using: $DATABASE_CONNECTION"
          echo "Using token key: $TOKEN_KEY"
          echo "FACEBOOK_SECRET: $FACEBOOK_SECRET"
          ECHO "GOOGLE_SECRET: $GOOGLE_SECRET"

      # Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BIZNET_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd HeavyEquipment
            cd HeavyEquipment-Be2.0
            git pull origin master
            sudo docker-compose down || true
            sudo docker-compose pull
            sudo docker-compose up -d --build
